<?php


return array(
    array(
        "name" => "Russian Federation (Российская Федерация)",
        "mask" => "+#(###) ###-##-##",
        "code" => "+7",
        "countryCode" => "ru",
        "phone" => "+7(999) 999-99-99",
    ),
    array(
        "name" => "Afghanistan (افغانستان)",
        "mask" => "+##-##-###-####",
        "code" => "+93",
        "countryCode" => "af",
        "phone" => "+93-99-999-9999",
    ),
    array(
        "name" => "Albania (Shqipëri)",
        "mask" => "+###(###) ###-###",
        "code" => "+355",
        "countryCode" => "al",
        "phone" => "+355(999) 999-999",
    ),
    array(
        "name" => "Algeria (الجزائر)",
        "mask" => "+###-##-###-####",
        "code" => "+213",
        "countryCode" => "dz",
        "phone" => "+213-99-999-9999",
    ),
    array(
        "name" => "Andorra",
        "mask" => "+###-###-###",
        "code" => "+376",
        "countryCode" => "ad",
        "phone" => "+376-999-999",
    ),
    array(
        "name" => "Angola",
        "mask" => "+###(###) ###-###",
        "code" => "+244",
        "countryCode" => "ao",
        "phone" => "+244(999) 999-999",
    ),
    array(
        "name" => "Armenia (Հայաստան)",
        "mask" => "+###-##-###-###",
        "code" => "+374",
        "countryCode" => "am",
        "phone" => "+374-99-999-999",
    ),
    array(
        "name" => "Antigua and Barbuda",
        "mask" => "+# (###)###-####",
        "code" => "+1 (268)",
        "countryCode" => "ag",
        "phone" => "+1 (268)999-9999",
    ),
    array(
        "name" => "Argentina",
        "mask" => "+##(###) ####-####",
        "code" => "+54",
        "countryCode" => "ar",
        "phone" => "+54(999) 9999-9999",
    ),
    array(
        "name" => "Australia",
        "mask" => "+##-##-####-####",
        "code" => "+61",
        "countryCode" => "au",
        "phone" => "+61-99-9999-9999",
    ),
    array(
        "name" => "Austria (Österreich)",
        "mask" => "+##(###) ###-#####",
        "code" => "+43",
        "countryCode" => "at",
        "phone" => "+43(999) 999-99999",
    ),
    array(
        "name" => "Azerbaijan (Azərbaycan)",
        "mask" => "+###-##-###-##-##",
        "code" => "+994",
        "countryCode" => "az",
        "phone" => "+994-99-999-99-99",
    ),
    array(
        "name" => "Bahamas",
        "mask" => "+# (###)###-####",
        "code" => "+1 (242)",
        "countryCode" => "bs",
        "phone" => "+1 (242)999-9999",
    ),
    array(
        "name" => "Bahrain (البحرين)",
        "mask" => "+###-####-####",
        "code" => "+973",
        "countryCode" => "bh",
        "phone" => "+973-9999-9999",
    ),
    array(
        "name" => "Bangladesh (বাংলাদেশ)",
        "mask" => "+###-####-######",
        "code" => "+880",
        "countryCode" => "bd",
        "phone" => "+880-9999-999999",
    ),
    array(
        "name" => "Barbados",
        "mask" => "+# (###)###-####",
        "code" => "+1 (246)",
        "countryCode" => "bb",
        "phone" => "+1 (246)999-9999",
    ),
    array(
        "name" => "Belarus (Беларусь)",
        "mask" => "+###(##) ###-##-##",
        "code" => "+375",
        "countryCode" => "by",
        "phone" => "+375(99) 999-99-99",
    ),
    array(
        "name" => "Belgium (België)",
        "mask" => "+##(###) ###-###",
        "code" => "+32",
        "countryCode" => "be",
        "phone" => "+32(999) 999-999",
    ),
    array(
        "name" => "Belize",
        "mask" => "+###-###-####",
        "code" => "+501",
        "countryCode" => "bz",
        "phone" => "+501-999-9999",
    ),
    array(
        "name" => "Benin (Bénin)",
        "mask" => "+###-##-##-####",
        "code" => "+229",
        "countryCode" => "bj",
        "phone" => "+229-99-99-9999",
    ),
    array(
        "name" => "Bhutan (འབྲུག)",
        "mask" => "+###-#-###-####",
        "code" => "+975",
        "countryCode" => "bt",
        "phone" => "+975-9-999-9999",
    ),
    array(
        "name" => "Bolivia",
        "mask" => "+###-#-###-####",
        "code" => "+591",
        "countryCode" => "bo",
        "phone" => "+591-9-999-9999",
    ),
    array(
        "name" => "Bosnia and Herzegovina",
        "mask" => "+###-##-###-###",
        "code" => "+387",
        "countryCode" => "ba",
        "phone" => "+387-99-999-999",
    ),
    array(
        "name" => "Botswana",
        "mask" => "+###-##-###-###",
        "code" => "+267",
        "countryCode" => "bw",
        "phone" => "+267-99-999-999",
    ),
    array(
        "name" => "Brazil (Brasil)",
        "mask" => "+##(##) #####-####",
        "code" => "+55",
        "countryCode" => "br",
        "phone" => "+55(99) 99999-9999",
    ),
    array(
        "name" => "Brunei",
        "mask" => "+###-###-####",
        "code" => "+673",
        "countryCode" => "bn",
        "phone" => "+673-999-9999",
    ),
    array(
        "name" => "Bulgaria (България)",
        "mask" => "+###(###) ###-###",
        "code" => "+359",
        "countryCode" => "bg",
        "phone" => "+359(999) 999-999",
    ),
    array(
        "name" => "Burkina Faso",
        "mask" => "+###-##-##-####",
        "code" => "+226",
        "countryCode" => "bf",
        "phone" => "+226-99-99-9999",
    ),
    array(
        "name" => "Burundi (Uburundi)",
        "mask" => "+###-##-##-####",
        "code" => "+257",
        "countryCode" => "bi",
        "phone" => "+257-99-99-9999",
    ),
    array(
        "name" => "Cambodia (កម្ពុជា)",
        "mask" => "+###-##-###-###",
        "code" => "+855",
        "countryCode" => "kh",
        "phone" => "+855-99-999-999",
    ),
    array(
        "name" => "Cameroon (Cameroun)",
        "mask" => "+###-#-##-##-##-##",
        "code" => "+237",
        "countryCode" => "cm",
        "phone" => "+237-9-99-99-99-99",
    ),
    array(
        "name" => "Canada",
        "mask" => "+#(###) ###-####",
        "code" => "+1",
        "countryCode" => "ca",
        "phone" => "+1(999) 999-9999",
    ),
    array(
        "name" => "Cape Verde (Kabu Verdi)",
        "mask" => "+###(###) ##-##",
        "code" => "+238",
        "countryCode" => "cv",
        "phone" => "+238(999) 99-99",
    ),
    array(
        "name" => "Central African Republic (République centrafricaine)",
        "mask" => "+###-##-##-####",
        "code" => "+236",
        "countryCode" => "cf",
        "phone" => "+236-99-99-9999",
    ),
    array(
        "name" => "Chad (Tchad)",
        "mask" => "+###-##-##-##-##",
        "code" => "+235",
        "countryCode" => "td",
        "phone" => "+235-99-99-99-99",
    ),
    array(
        "name" => "Chile",
        "mask" => "+##-#-####-####",
        "code" => "+56",
        "countryCode" => "cl",
        "phone" => "+56-9-9999-9999",
    ),
    array(
        "name" => "China (中国)",
        "mask" => "+##(###) ####-####",
        "code" => "+86",
        "countryCode" => "cn",
        "phone" => "+86(999) 9999-9999",
    ),
    array(
        "name" => "Colombia",
        "mask" => "+##(###) ###-####",
        "code" => "+57",
        "countryCode" => "co",
        "phone" => "+57(999) 999-9999",
    ),
    array(
        "name" => "Comoros (جزر القمر)",
        "mask" => "+###-##-#####",
        "code" => "+269",
        "countryCode" => "km",
        "phone" => "+269-99-99999",
    ),
    array(
        "name" => "Congo (DRC) (Jamhuri ya Kidemokrasia ya Kongo)",
        "mask" => "+###(###) ###-###",
        "code" => "+243",
        "countryCode" => "cd",
        "phone" => "+243(999) 999-999",
    ),
    array(
        "name" => "Congo (Republic) (Congo-Brazzaville)",
        "mask" => "+###-##-###-####",
        "code" => "+242",
        "countryCode" => "cg",
        "phone" => "+242-99-999-9999",
    ),
    array(
        "name" => "Cook Islands",
        "mask" => "+###-##-###",
        "code" => "+682",
        "countryCode" => "ck",
        "phone" => "+682-99-999",
    ),
    array(
        "name" => "Costa Rica",
        "mask" => "+###-####-####",
        "code" => "+506",
        "countryCode" => "cr",
        "phone" => "+506-9999-9999",
    ),
    array(
        "name" => "Cote d’Ivoire",
        "mask" => "+###-##-###-###",
        "code" => "+225",
        "countryCode" => "ci",
        "phone" => "+225-99-999-999",
    ),
    array(
        "name" => "Croatia (Hrvatska)",
        "mask" => "+###-##-###-####",
        "code" => "+385",
        "countryCode" => "hr",
        "phone" => "+385-99-999-9999",
    ),
    array(
        "name" => "Cuba",
        "mask" => "+##-#-###-####",
        "code" => "+53",
        "countryCode" => "cu",
        "phone" => "+53-9-999-9999",
    ),
    array(
        "name" => "Cyprus (Κύπρος)",
        "mask" => "+###-##-###-###",
        "code" => "+357",
        "countryCode" => "cy",
        "phone" => "+357-99-999-999",
    ),
    array(
        "name" => "Czech Republic (Česká republika)",
        "mask" => "+###(###) ###-###",
        "code" => "+420",
        "countryCode" => "cz",
        "phone" => "+420(999) 999-999",
    ),
    array(
        "name" => "Denmark (Danmark)",
        "mask" => "+##-##-##-##-##",
        "code" => "+45",
        "countryCode" => "dk",
        "phone" => "+45-99-99-99-99",
    ),
    array(
        "name" => "Djibouti",
        "mask" => "+###-##-##-##-##",
        "code" => "+253",
        "countryCode" => "dj",
        "phone" => "+253-99-99-99-99",
    ),
    array(
        "name" => "Dominica",
        "mask" => "+# (###)###-####",
        "code" => "+1 (767)",
        "countryCode" => "dm",
        "phone" => "+1 (767)999-9999",
    ),
    array(
        "name" => "Dominican Republic (República Dominicana)",
        "mask" => "+#(###) ###-####",
        "code" => "+1",
        "countryCode" => "do",
        "phone" => "+1(999) 999-9999",
    ),
    array(
        "name" => "Ecuador",
        "mask" => "+###-##-###-####",
        "code" => "+593",
        "countryCode" => "ec",
        "phone" => "+593-99-999-9999",
    ),
    array(
        "name" => "Egypt (مصر)",
        "mask" => "+##(###) ###-####",
        "code" => "+20",
        "countryCode" => "eg",
        "phone" => "+20(999) 999-9999",
    ),
    array(
        "name" => "El Salvador",
        "mask" => "+###-##-##-####",
        "code" => "+503",
        "countryCode" => "sv",
        "phone" => "+503-99-99-9999",
    ),
    array(
        "name" => "Equatorial Guinea (Guinea Ecuatorial)",
        "mask" => "+###-##-###-####",
        "code" => "+240",
        "countryCode" => "gq",
        "phone" => "+240-99-999-9999",
    ),
    array(
        "name" => "Eritrea",
        "mask" => "+###-#-###-###",
        "code" => "+291",
        "countryCode" => "er",
        "phone" => "+291-9-999-999",
    ),
    array(
        "name" => "Estonia (Eesti)",
        "mask" => "+###-####-####",
        "code" => "+372",
        "countryCode" => "ee",
        "phone" => "+372-9999-9999",
    ),
    array(
        "name" => "Ethiopia",
        "mask" => "+###-##-###-####",
        "code" => "+251",
        "countryCode" => "et",
        "phone" => "+251-99-999-9999",
    ),
    array(
        "name" => "Fiji",
        "mask" => "+###-###-####",
        "code" => "+679",
        "countryCode" => "fj",
        "phone" => "+679-999-9999",
    ),
    array(
        "name" => "Finland (Suomi)",
        "mask" => "+###-###-#######",
        "code" => "+358",
        "countryCode" => "fi",
        "phone" => "+358-999-9999999",
    ),
    array(
        "name" => "France",
        "mask" => "+##(###) ###-####",
        "code" => "+33",
        "countryCode" => "fr",
        "phone" => "+33(999) 999-9999",
    ),
    array(
        "name" => "Gabon",
        "mask" => "+###-#-##-##-##",
        "code" => "+241",
        "countryCode" => "ga",
        "phone" => "+241-9-99-99-99",
    ),
    array(
        "name" => "Gambia",
        "mask" => "+###(###) ##-##",
        "code" => "+220",
        "countryCode" => "gm",
        "phone" => "+220(999) 99-99",
    ),
    array(
        "name" => "Georgia (საქართველო)",
        "mask" => "+###(###) ###-###",
        "code" => "+995",
        "countryCode" => "ge",
        "phone" => "+995(999) 999-999",
    ),
    array(
        "name" => "Germany (Deutschland)",
        "mask" => "+##(###) ###-#####",
        "code" => "+49",
        "countryCode" => "de",
        "phone" => "+49(999) 999-99999",
    ),
    array(
        "name" => "Ghana (Gaana)",
        "mask" => "+###(###) ###-###",
        "code" => "+233",
        "countryCode" => "gh",
        "phone" => "+233(999) 999-999",
    ),
    array(
        "name" => "Greece (Ελλάδα)",
        "mask" => "+##(###) ###-####",
        "code" => "+30",
        "countryCode" => "gr",
        "phone" => "+30(999) 999-9999",
    ),
    array(
        "name" => "Grenada",
        "mask" => "+# (###)###-####",
        "code" => "+1 (473)",
        "countryCode" => "gd",
        "phone" => "+1 (473)999-9999",
    ),
    array(
        "name" => "Guatemala",
        "mask" => "+###-#-###-####",
        "code" => "+502",
        "countryCode" => "gt",
        "phone" => "+502-9-999-9999",
    ),
    array(
        "name" => "Guinea (Guinée)",
        "mask" => "+###-###-##-##-##",
        "code" => "+224",
        "countryCode" => "gn",
        "phone" => "+224-999-99-99-99",
    ),
    array(
        "name" => "Guinea-Bissau (Guiné Bissau)",
        "mask" => "+###-#-######",
        "code" => "+245",
        "countryCode" => "gw",
        "phone" => "+245-9-999999",
    ),
    array(
        "name" => "Guyana",
        "mask" => "+###-###-####",
        "code" => "+592",
        "countryCode" => "gy",
        "phone" => "+592-999-9999",
    ),
    array(
        "name" => "Haiti",
        "mask" => "+###-##-##-####",
        "code" => "+509",
        "countryCode" => "ht",
        "phone" => "+509-99-99-9999",
    ),
    array(
        "name" => "Honduras",
        "mask" => "+###-####-####",
        "code" => "+504",
        "countryCode" => "hn",
        "phone" => "+504-9999-9999",
    ),
    array(
        "name" => "Hong Kong (香港)",
        "mask" => "+###-####-####",
        "code" => "+852",
        "countryCode" => "hk",
        "phone" => "+852-9999-9999",
    ),
    array(
        "name" => "Hungary (Magyarország)",
        "mask" => "+##(###) ###-###",
        "code" => "+36",
        "countryCode" => "hu",
        "phone" => "+36(999) 999-999",
    ),
    array(
        "name" => "Iceland (Ísland)",
        "mask" => "+###-###-####",
        "code" => "+354",
        "countryCode" => "is",
        "phone" => "+354-999-9999",
    ),
    array(
        "name" => "India (भारत)",
        "mask" => "+##(####) ###-###",
        "code" => "+91",
        "countryCode" => "in",
        "phone" => "+91(9999) 999-999",
    ),
    array(
        "name" => "Indonesia",
        "mask" => "+##(###) ###-##-####",
        "code" => "+62",
        "countryCode" => "id",
        "phone" => "+62(999) 999-99-9999",
    ),
    array(
        "name" => "Iran (ایران)",
        "mask" => "+##(###) ###-####",
        "code" => "+98",
        "countryCode" => "ir",
        "phone" => "+98(999) 999-9999",
    ),
    array(
        "name" => "Iraq (العراق)",
        "mask" => "+###(###) ###-####",
        "code" => "+964",
        "countryCode" => "iq",
        "phone" => "+964(999) 999-9999",
    ),
    array(
        "name" => "Ireland",
        "mask" => "+###(###) ###-###",
        "code" => "+353",
        "countryCode" => "ie",
        "phone" => "+353(999) 999-999",
    ),
    array(
        "name" => "Israel (ישראל)",
        "mask" => "+###-###-###-####",
        "code" => "+972",
        "countryCode" => "il",
        "phone" => "+972-999-999-9999",
    ),
    array(
        "name" => "Italy (Italia)",
        "mask" => "+##(###) ####-###",
        "code" => "+39",
        "countryCode" => "it",
        "phone" => "+39(999) 9999-999",
    ),
    array(
        "name" => "Jamaica",
        "mask" => "+#(###) ###-####",
        "code" => "+1",
        "countryCode" => "jm",
        "phone" => "+1(999) 999-9999",
    ),
    array(
        "name" => "Japan (日本)",
        "mask" => "+##-##-####-####",
        "code" => "+81",
        "countryCode" => "jp",
        "phone" => "+81-99-9999-9999",
    ),
    array(
        "name" => "Jordan (الأردن)",
        "mask" => "+###-#-####-####",
        "code" => "+962",
        "countryCode" => "jo",
        "phone" => "+962-9-9999-9999",
    ),
    array(
        "name" => "Kazakhstan (Казахстан)",
        "mask" => "+#(###) ###-##-##",
        "code" => "+7",
        "countryCode" => "kz",
        "phone" => "+7(999) 999-99-99",
    ),
    array(
        "name" => "Kenya",
        "mask" => "+###-###-######",
        "code" => "+254",
        "countryCode" => "ke",
        "phone" => "+254-999-999999",
    ),
    array(
        "name" => "Kiribati",
        "mask" => "+###-##-###",
        "code" => "+686",
        "countryCode" => "ki",
        "phone" => "+686-99-999",
    ),
    array(
        "name" => "Kosovo (Republic)",
        "mask" => "+###-##-###-###",
        "code" => "+383",
        "countryCode" => "xk",
        "phone" => "+383-99-999-999",
    ),
    array(
        "name" => "Kuwait (الكويت)",
        "mask" => "+###-####-####",
        "code" => "+965",
        "countryCode" => "kw",
        "phone" => "+965-9999-9999",
    ),
    array(
        "name" => "Kyrgyzstan (Кыргызстан)",
        "mask" => "+###(###) ###-###",
        "code" => "+996",
        "countryCode" => "kg",
        "phone" => "+996(999) 999-999",
    ),
    array(
        "name" => "Laos (ລາວ)",
        "mask" => "+###-##-###-###",
        "code" => "+856",
        "countryCode" => "la",
        "phone" => "+856-99-999-999",
    ),
    array(
        "name" => "Latvia (Latvija)",
        "mask" => "+###-##-###-###",
        "code" => "+371",
        "countryCode" => "lv",
        "phone" => "+371-99-999-999",
    ),
    array(
        "name" => "Lebanon (لبنان)",
        "mask" => "+###-##-###-###",
        "code" => "+961",
        "countryCode" => "lb",
        "phone" => "+961-99-999-999",
    ),
    array(
        "name" => "Lesotho",
        "mask" => "+###-#-###-####",
        "code" => "+266",
        "countryCode" => "ls",
        "phone" => "+266-9-999-9999",
    ),
    array(
        "name" => "Liberia",
        "mask" => "+###-##-###-####",
        "code" => "+231",
        "countryCode" => "lr",
        "phone" => "+231-99-999-9999",
    ),
    array(
        "name" => "Libya (ليبيا)",
        "mask" => "+###-##-###-###",
        "code" => "+218",
        "countryCode" => "ly",
        "phone" => "+218-99-999-999",
    ),
    array(
        "name" => "Liechtenstein",
        "mask" => "+###-###-##-##",
        "code" => "+423",
        "countryCode" => "li",
        "phone" => "+423-999-99-99",
    ),
    array(
        "name" => "Lithuania (Lietuva)",
        "mask" => "+###(###) ##-###",
        "code" => "+370",
        "countryCode" => "lt",
        "phone" => "+370(999) 99-999",
    ),
    array(
        "name" => "Luxembourg",
        "mask" => "+###(###) ###-###",
        "code" => "+352",
        "countryCode" => "lu",
        "phone" => "+352(999) 999-999",
    ),
    array(
        "name" => "Macao",
        "mask" => "+###-####-####",
        "code" => "+853",
        "countryCode" => "mo",
        "phone" => "+853-9999-9999",
    ),
    array(
        "name" => "Macedonia (FYROM) (Македонија)",
        "mask" => "+###-##-###-###",
        "code" => "+389",
        "countryCode" => "mk",
        "phone" => "+389-99-999-999",
    ),
    array(
        "name" => "Madagascar (Madagasikara)",
        "mask" => "+###-##-##-#####",
        "code" => "+261",
        "countryCode" => "mg",
        "phone" => "+261-99-99-99999",
    ),
    array(
        "name" => "Malawi",
        "mask" => "+###-#-####-####",
        "code" => "+265",
        "countryCode" => "mw",
        "phone" => "+265-9-9999-9999",
    ),
    array(
        "name" => "Malaysia",
        "mask" => "+##-##-###-####",
        "code" => "+60",
        "countryCode" => "my",
        "phone" => "+60-99-999-9999",
    ),
    array(
        "name" => "Maldives",
        "mask" => "+###-###-####",
        "code" => "+960",
        "countryCode" => "mv",
        "phone" => "+960-999-9999",
    ),
    array(
        "name" => "Mali",
        "mask" => "+###-##-##-####",
        "code" => "+223",
        "countryCode" => "ml",
        "phone" => "+223-99-99-9999",
    ),
    array(
        "name" => "Malta",
        "mask" => "+###-####-####",
        "code" => "+356",
        "countryCode" => "mt",
        "phone" => "+356-9999-9999",
    ),
    array(
        "name" => "Marshall Islands",
        "mask" => "+###-###-####",
        "code" => "+692",
        "countryCode" => "mh",
        "phone" => "+692-999-9999",
    ),
    array(
        "name" => "Mauritania (موريتانيا)",
        "mask" => "+###-##-##-####",
        "code" => "+222",
        "countryCode" => "mr",
        "phone" => "+222-99-99-9999",
    ),
    array(
        "name" => "Mauritius (Moris)",
        "mask" => "+###-###-#####",
        "code" => "+230",
        "countryCode" => "mu",
        "phone" => "+230-999-99999",
    ),
    array(
        "name" => "Mexico (México)",
        "mask" => "+##(###) ###-####",
        "code" => "+52",
        "countryCode" => "mx",
        "phone" => "+52(999) 999-9999",
    ),
    array(
        "name" => "Mexico (México)",
        "mask" => "+###(###) ###-####",
        "code" => "+521",
        "countryCode" => "mb",
        "phone" => "+521(999) 999-9999",
    ),
    array(
        "name" => "Micronesia",
        "mask" => "+###-###-####",
        "code" => "+691",
        "countryCode" => "fm",
        "phone" => "+691-999-9999",
    ),
    array(
        "name" => "Moldova (Republica Moldova)",
        "mask" => "+###-####-####",
        "code" => "+373",
        "countryCode" => "md",
        "phone" => "+373-9999-9999",
    ),
    array(
        "name" => "Monaco",
        "mask" => "+###-##-###-###",
        "code" => "+377",
        "countryCode" => "mc",
        "phone" => "+377-99-999-999",
    ),
    array(
        "name" => "Mongolia (Монгол)",
        "mask" => "+###-##-##-####",
        "code" => "+976",
        "countryCode" => "mn",
        "phone" => "+976-99-99-9999",
    ),
    array(
        "name" => "Montenegro (Crna Gora)",
        "mask" => "+###-##-###-###",
        "code" => "+382",
        "countryCode" => "me",
        "phone" => "+382-99-999-999",
    ),
    array(
        "name" => "Morocco (المغرب)",
        "mask" => "+###-##-####-###",
        "code" => "+212",
        "countryCode" => "ma",
        "phone" => "+212-99-9999-999",
    ),
    array(
        "name" => "Mozambique (Moçambique)",
        "mask" => "+###-##-###-###",
        "code" => "+258",
        "countryCode" => "mz",
        "phone" => "+258-99-999-999",
    ),
    array(
        "name" => "Myanmar (Burma) (မြန်မာ)",
        "mask" => "+##-##-###-###",
        "code" => "+95",
        "countryCode" => "mm",
        "phone" => "+95-99-999-999",
    ),
    array(
        "name" => "Namibia (Namibië)",
        "mask" => "+###-##-###-####",
        "code" => "+264",
        "countryCode" => "na",
        "phone" => "+264-99-999-9999",
    ),
    array(
        "name" => "Nauru",
        "mask" => "+###-###-####",
        "code" => "+674",
        "countryCode" => "nr",
        "phone" => "+674-999-9999",
    ),
    array(
        "name" => "Nepal (नेपाल)",
        "mask" => "+###-###-###-####",
        "code" => "+977",
        "countryCode" => "np",
        "phone" => "+977-999-999-9999",
    ),
    array(
        "name" => "Netherlands (Nederland)",
        "mask" => "+##-##-###-####",
        "code" => "+31",
        "countryCode" => "nl",
        "phone" => "+31-99-999-9999",
    ),
    array(
        "name" => "New Zealand",
        "mask" => "+##(###) ###-###",
        "code" => "+64",
        "countryCode" => "nz",
        "phone" => "+64(999) 999-999",
    ),
    array(
        "name" => "Nicaragua",
        "mask" => "+###-####-####",
        "code" => "+505",
        "countryCode" => "ni",
        "phone" => "+505-9999-9999",
    ),
    array(
        "name" => "Niger (Nijar)",
        "mask" => "+###-##-##-####",
        "code" => "+227",
        "countryCode" => "ne",
        "phone" => "+227-99-99-9999",
    ),
    array(
        "name" => "Nigeria",
        "mask" => "+###-###-###-####",
        "code" => "+234",
        "countryCode" => "ng",
        "phone" => "+234-999-999-9999",
    ),
    array(
        "name" => "Niue",
        "mask" => "+###-####",
        "code" => "+683",
        "countryCode" => "nu",
        "phone" => "+683-9999",
    ),
    array(
        "name" => "North Korea (조선 민주주의 인민 공화국)",
        "mask" => "+###-##-###-###",
        "code" => "+850",
        "countryCode" => "kp",
        "phone" => "+850-99-999-999",
    ),
    array(
        "name" => "Norway (Norge)",
        "mask" => "+##(###) ##-###",
        "code" => "+47",
        "countryCode" => "no",
        "phone" => "+47(999) 99-999",
    ),
    array(
        "name" => "Oman (عُمان)",
        "mask" => "+###-##-###-###",
        "code" => "+968",
        "countryCode" => "om",
        "phone" => "+968-99-999-999",
    ),
    array(
        "name" => "Panama",
        "mask" => "+###-####-####",
        "code" => "+507",
        "countryCode" => "pa",
        "phone" => "+507-9999-9999",
    ),
    array(
        "name" => "Pakistan (پاکستان)",
        "mask" => "+##(###) ###-####",
        "code" => "+92",
        "countryCode" => "pk",
        "phone" => "+92(999) 999-9999",
    ),
    array(
        "name" => "Palau",
        "mask" => "+###-###-####",
        "code" => "+680",
        "countryCode" => "pw",
        "phone" => "+680-999-9999",
    ),
    array(
        "name" => "Palestinian Territory",
        "mask" => "+###-## ### ####",
        "code" => "+970",
        "countryCode" => "ps",
        "phone" => "+970-99 999 9999",
    ),
    array(
        "name" => "Papua New Guinea",
        "mask" => "+###(###) ##-###",
        "code" => "+675",
        "countryCode" => "pg",
        "phone" => "+675(999) 99-999",
    ),
    array(
        "name" => "Paraguay",
        "mask" => "+###(###) ###-###",
        "code" => "+595",
        "countryCode" => "py",
        "phone" => "+595(999) 999-999",
    ),
    array(
        "name" => "Peru (Perú)",
        "mask" => "+##(###) ###-###",
        "code" => "+51",
        "countryCode" => "pe",
        "phone" => "+51(999) 999-999",
    ),
    array(
        "name" => "Philippines",
        "mask" => "+##(###) ###-####",
        "code" => "+63",
        "countryCode" => "ph",
        "phone" => "+63(999) 999-9999",
    ),
    array(
        "name" => "Poland (Polska)",
        "mask" => "+##(###) ###-###",
        "code" => "+48",
        "countryCode" => "pl",
        "phone" => "+48(999) 999-999",
    ),
    array(
        "name" => "Portugal",
        "mask" => "+###-##-###-####",
        "code" => "+351",
        "countryCode" => "pt",
        "phone" => "+351-99-999-9999",
    ),
    array(
        "name" => "Qatar (قطر)",
        "mask" => "+###-####-####",
        "code" => "+974",
        "countryCode" => "qa",
        "phone" => "+974-9999-9999",
    ),
    array(
        "name" => "Romania (România)",
        "mask" => "+##-##-###-####",
        "code" => "+40",
        "countryCode" => "ro",
        "phone" => "+40-99-999-9999",
    ),
    array(
        "name" => "Rwanda",
        "mask" => "+###(###) ###-###",
        "code" => "+250",
        "countryCode" => "rw",
        "phone" => "+250(999) 999-999",
    ),
    array(
        "name" => "Saint Kitts and Nevis",
        "mask" => "+# (###)###-####",
        "code" => "+1 (869)",
        "countryCode" => "kn",
        "phone" => "+1 (869)999-9999",
    ),
    array(
        "name" => "Saint Lucia",
        "mask" => "+# (###)###-####",
        "code" => "+1 (758)",
        "countryCode" => "lc",
        "phone" => "+1 (758)999-9999",
    ),
    array(
        "name" => "Saint Vincent and the Grenadines",
        "mask" => "+# (###)###-####",
        "code" => "+1 (784)",
        "countryCode" => "vc",
        "phone" => "+1 (784)999-9999",
    ),
    array(
        "name" => "Samoa",
        "mask" => "+###-##-####",
        "code" => "+685",
        "countryCode" => "ws",
        "phone" => "+685-99-9999",
    ),
    array(
        "name" => "San Marino",
        "mask" => "+###-####-######",
        "code" => "+378",
        "countryCode" => "sm",
        "phone" => "+378-9999-999999",
    ),
    array(
        "name" => "Sao Tome and Principe (São Tomé e Príncipe)",
        "mask" => "+###-##-#####",
        "code" => "+239",
        "countryCode" => "st",
        "phone" => "+239-99-99999",
    ),
    array(
        "name" => "Saudi Arabia (المملكة العربية السعودية)",
        "mask" => "+###-#-####-####",
        "code" => "+966",
        "countryCode" => "sa",
        "phone" => "+966-9-9999-9999",
    ),
    array(
        "name" => "Senegal (Sénégal)",
        "mask" => "+###-##-###-####",
        "code" => "+221",
        "countryCode" => "sn",
        "phone" => "+221-99-999-9999",
    ),
    array(
        "name" => "Serbia (Србија)",
        "mask" => "+###-##-###-####",
        "code" => "+381",
        "countryCode" => "rs",
        "phone" => "+381-99-999-9999",
    ),
    array(
        "name" => "Seychelles",
        "mask" => "+###-#-###-###",
        "code" => "+248",
        "countryCode" => "sc",
        "phone" => "+248-9-999-999",
    ),
    array(
        "name" => "Sierra Leone",
        "mask" => "+###-##-######",
        "code" => "+232",
        "countryCode" => "sl",
        "phone" => "+232-99-999999",
    ),
    array(
        "name" => "Singapore",
        "mask" => "+##-####-####",
        "code" => "+65",
        "countryCode" => "sg",
        "phone" => "+65-9999-9999",
    ),
    array(
        "name" => "Slovakia (Slovensko)",
        "mask" => "+###(###) ###-###",
        "code" => "+421",
        "countryCode" => "sk",
        "phone" => "+421(999) 999-999",
    ),
    array(
        "name" => "Slovenia (Slovenija)",
        "mask" => "+###-##-###-###",
        "code" => "+386",
        "countryCode" => "si",
        "phone" => "+386-99-999-999",
    ),
    array(
        "name" => "Solomon Islands",
        "mask" => "+###-###-####",
        "code" => "+677",
        "countryCode" => "sb",
        "phone" => "+677-999-9999",
    ),
    array(
        "name" => "Somalia (Soomaaliya)",
        "mask" => "+###-##-###-###",
        "code" => "+252",
        "countryCode" => "so",
        "phone" => "+252-99-999-999",
    ),
    array(
        "name" => "South Africa",
        "mask" => "+##-##-###-####",
        "code" => "+27",
        "countryCode" => "za",
        "phone" => "+27-99-999-9999",
    ),
    array(
        "name" => "South Korea (대한민국)",
        "mask" => "+##-##-####-####",
        "code" => "+82",
        "countryCode" => "kr",
        "phone" => "+82-99-9999-9999",
    ),
    array(
        "name" => "South Sudan (جنوب السودان)",
        "mask" => "+###-##-###-####",
        "code" => "+211",
        "countryCode" => "ss",
        "phone" => "+211-99-999-9999",
    ),
    array(
        "name" => "Spain (España)",
        "mask" => "+##(###) ###-###",
        "code" => "+34",
        "countryCode" => "es",
        "phone" => "+34(999) 999-999",
    ),
    array(
        "name" => "Sri Lanka (ශ්‍රී ලංකාව)",
        "mask" => "+##-##-###-####",
        "code" => "+94",
        "countryCode" => "lk",
        "phone" => "+94-99-999-9999",
    ),
    array(
        "name" => "Sudan (السودان)",
        "mask" => "+###-##-###-####",
        "code" => "+249",
        "countryCode" => "sd",
        "phone" => "+249-99-999-9999",
    ),
    array(
        "name" => "Suriname",
        "mask" => "+###-###-####",
        "code" => "+597",
        "countryCode" => "sr",
        "phone" => "+597-999-9999",
    ),
    array(
        "name" => "Swaziland",
        "mask" => "+###-##-##-####",
        "code" => "+268",
        "countryCode" => "sz",
        "phone" => "+268-99-99-9999",
    ),
    array(
        "name" => "Sweden (Sverige)",
        "mask" => "+##-##-###-####",
        "code" => "+46",
        "countryCode" => "se",
        "phone" => "+46-99-999-9999",
    ),
    array(
        "name" => "Switzerland (Schweiz)",
        "mask" => "+##-##-###-####",
        "code" => "+41",
        "countryCode" => "ch",
        "phone" => "+41-99-999-9999",
    ),
    array(
        "name" => "Syria (سوريا)",
        "mask" => "+###-##-####-###",
        "code" => "+963",
        "countryCode" => "sy",
        "phone" => "+963-99-9999-999",
    ),
    array(
        "name" => "Taiwan (台灣)",
        "mask" => "+###-####-####",
        "code" => "+886",
        "countryCode" => "tw",
        "phone" => "+886-9999-9999",
    ),
    array(
        "name" => "Tajikistan",
        "mask" => "+###-##-###-####",
        "code" => "+992",
        "countryCode" => "tj",
        "phone" => "+992-99-999-9999",
    ),
    array(
        "name" => "Tanzania",
        "mask" => "+###-##-###-####",
        "code" => "+255",
        "countryCode" => "tz",
        "phone" => "+255-99-999-9999",
    ),
    array(
        "name" => "Thailand (ไทย)",
        "mask" => "+##-##-###-####",
        "code" => "+66",
        "countryCode" => "th",
        "phone" => "+66-99-999-9999",
    ),
    array(
        "name" => "Togo",
        "mask" => "+###-##-###-###",
        "code" => "+228",
        "countryCode" => "tg",
        "phone" => "+228-99-999-999",
    ),
    array(
        "name" => "Tonga",
        "mask" => "+###-#####",
        "code" => "+676",
        "countryCode" => "to",
        "phone" => "+676-99999",
    ),
    array(
        "name" => "Trinidad and Tobago",
        "mask" => "+# (###)###-####",
        "code" => "+1 (868)",
        "countryCode" => "tt",
        "phone" => "+1 (868)999-9999",
    ),
    array(
        "name" => "Tunisia (تونس)",
        "mask" => "+###-##-###-###",
        "code" => "+216",
        "countryCode" => "tn",
        "phone" => "+216-99-999-999",
    ),
    array(
        "name" => "Turkey (Türkiye)",
        "mask" => "+##(###) ###-#####",
        "code" => "+90",
        "countryCode" => "tr",
        "phone" => "+90(999) 999-99999",
    ),
    array(
        "name" => "Turkmenistan",
        "mask" => "+###-#-###-####",
        "code" => "+993",
        "countryCode" => "tm",
        "phone" => "+993-9-999-9999",
    ),
    array(
        "name" => "Tuvalu",
        "mask" => "+###-######",
        "code" => "+688",
        "countryCode" => "tv",
        "phone" => "+688-999999",
    ),
    array(
        "name" => "Uganda",
        "mask" => "+###(###) ###-###",
        "code" => "+256",
        "countryCode" => "ug",
        "phone" => "+256(999) 999-999",
    ),
    array(
        "name" => "Ukraine (Україна)",
        "mask" => "+###(##) ###-##-##",
        "code" => "+380",
        "countryCode" => "ua",
        "phone" => "+380(99) 999-99-99",
    ),
    array(
        "name" => "United Arab Emirates (الإمارات العربية المتحدة)",
        "mask" => "+###-##-###-####",
        "code" => "+971",
        "countryCode" => "ae",
        "phone" => "+971-99-999-9999",
    ),
    array(
        "name" => "United Kingdom",
        "mask" => "+##-##-####-#####",
        "code" => "+44",
        "countryCode" => "gb",
        "phone" => "+44-99-9999-99999",
    ),
    array(
        "name" => "USA",
        "mask" => "+#(###) ###-####",
        "code" => "+1",
        "countryCode" => "us",
        "phone" => "+1(999) 999-9999",
    ),
    array(
        "name" => "Uruguay",
        "mask" => "+###-#-###-##-##",
        "code" => "+598",
        "countryCode" => "uy",
        "phone" => "+598-9-999-99-99",
    ),
    array(
        "name" => "Uzbekistan (Oʻzbekiston)",
        "mask" => "+###-##-###-####",
        "code" => "+998",
        "countryCode" => "uz",
        "phone" => "+998-99-999-9999",
    ),
    array(
        "name" => "Vanuatu",
        "mask" => "+###-##-#####",
        "code" => "+678",
        "countryCode" => "vu",
        "phone" => "+678-99-99999",
    ),
    array(
        "name" => "Vatican City (Città del Vaticano)",
        "mask" => "+##-#-###-#####",
        "code" => "+39",
        "countryCode" => "va",
        "phone" => "+39-9-999-99999",
    ),
    array(
        "name" => "Venezuela",
        "mask" => "+##(###) ###-####",
        "code" => "+58",
        "countryCode" => "ve",
        "phone" => "+58(999) 999-9999",
    ),
    array(
        "name" => "Vietnam (Việt Nam)",
        "mask" => "+##-##-####-###",
        "code" => "+84",
        "countryCode" => "vn",
        "phone" => "+84-99-9999-999",
    ),
    array(
        "name" => "Yemen (اليمن)",
        "mask" => "+###-#-###-###",
        "code" => "+967",
        "countryCode" => "ye",
        "phone" => "+967-9-999-999",
    ),
    array(
        "name" => "Zambia",
        "mask" => "+###-##-###-####",
        "code" => "+260",
        "countryCode" => "zm",
        "phone" => "+260-99-999-9999",
    ),
    array(
        "name" => "Zimbabwe",
        "mask" => "+###-#-######",
        "code" => "+263",
        "countryCode" => "zw",
        "phone" => "+263-9-999999",
    ),
);
