<?php

const NETCAT_MODULE_LOGGING_DESCRIPTION = "Logging system actions.";

const NETCAT_MODULE_LOGGING_DATA_ID = "#";
const NETCAT_MODULE_LOGGING_DATA_EVENT = "Action";
const NETCAT_MODULE_LOGGING_DATA_INFO = "Information";
const NETCAT_MODULE_LOGGING_DATA_DATE = "Date";
const NETCAT_MODULE_LOGGING_DATA_USER = "User";
const NETCAT_MODULE_LOGGING_DATA_SYSTEM = "system";
const NETCAT_MODULE_LOGGING_IP = "IP address";

const NETCAT_MODULE_LOGGING_BUTTON_CLEAR = "Clear";
const NETCAT_MODULE_LOGGING_BUTTON_CANCEL = "Cancel";
const NETCAT_MODULE_LOGGING_BUTTON_SORT = "Display";

const NETCAT_MODULE_LOGGING_NOTICE_CLEAR = "Clear all logging data?";

const NETCAT_MODULE_LOGGING_SHOW_PARAMETERS = "Display options";
const NETCAT_MODULE_LOGGING_SHOW_SORT_BY = "sort by";
const NETCAT_MODULE_LOGGING_SHOW_SORT_BY_DATE = "date";
const NETCAT_MODULE_LOGGING_SHOW_SORT_BY_EVENT = "action";
const NETCAT_MODULE_LOGGING_SHOW_SORT_BY_USER = "user";
const NETCAT_MODULE_LOGGING_SHOW_SORT_DIR = "sort direction";
const NETCAT_MODULE_LOGGING_SHOW_SORT_DIR_ASC = "ascending";
const NETCAT_MODULE_LOGGING_SHOW_SORT_DIR_DESC = "descending";
const NETCAT_MODULE_LOGGING_SHOW_ONLY_ACTION = "display action";
const NETCAT_MODULE_LOGGING_SHOW_ONLY_ACTION_NONE = "-- action is not set --";
const NETCAT_MODULE_LOGGING_SHOW_ONLY_ESSENCE = "display item";
const NETCAT_MODULE_LOGGING_SHOW_ONLY_ESSENCE_NONE = "-- essence is not set --";

const NETCAT_MODULE_LOGGING_EVENT_TYPE_ADD = "add";
const NETCAT_MODULE_LOGGING_EVENT_TYPE_UPDATE = "update";
const NETCAT_MODULE_LOGGING_EVENT_TYPE_DROP = "drop";
const NETCAT_MODULE_LOGGING_EVENT_TYPE_CHECK = "check";
const NETCAT_MODULE_LOGGING_EVENT_TYPE_UNCHECK = "uncheck";
const NETCAT_MODULE_LOGGING_EVENT_TYPE_AUTHORIZE = "authorize";
const NETCAT_MODULE_LOGGING_EVENT_TYPE_BLOCK = "block";
const NETCAT_MODULE_LOGGING_EVENT_TYPE_UNBLOCK = "unblock";

const NETCAT_MODULE_LOGGING_EVENT_ESSENCE_CATALOGUE = "site";
const NETCAT_MODULE_LOGGING_EVENT_ESSENCE_SUBDIVISION = "subdivision";
const NETCAT_MODULE_LOGGING_EVENT_ESSENCE_SUBCLASS = "infoblock";
const NETCAT_MODULE_LOGGING_EVENT_ESSENCE_CLASS = "component";
const NETCAT_MODULE_LOGGING_EVENT_ESSENCE_CLASSTEMPLATE = "component template";
const NETCAT_MODULE_LOGGING_EVENT_ESSENCE_MESSAGE = "message";
const NETCAT_MODULE_LOGGING_EVENT_ESSENCE_SYSTEMTABLE = "system table";
const NETCAT_MODULE_LOGGING_EVENT_ESSENCE_TEMPLATE = "design template";
const NETCAT_MODULE_LOGGING_EVENT_ESSENCE_USER = "user";
const NETCAT_MODULE_LOGGING_EVENT_ESSENCE_MODULE = "module";
const NETCAT_MODULE_LOGGING_EVENT_ESSENCE_COMMENT = "comments";
const NETCAT_MODULE_LOGGING_EVENT_ESSENCE_WIDGETCLASS = "widget";
const NETCAT_MODULE_LOGGING_EVENT_ESSENCE_FIELD = "field";
const NETCAT_MODULE_LOGGING_EVENT_ESSENCE_CLASSIFICATOR = "classificator";
const NETCAT_MODULE_LOGGING_EVENT_ESSENCE_CLASSIFICATORITEM = "classificator item";
const NETCAT_MODULE_LOGGING_EVENT_ESSENCE_TEMPLATEPARTIAL = "partial";

const NETCAT_MODULE_LOGGING_QUOTE1 = "“";
const NETCAT_MODULE_LOGGING_QUOTE2 = "”";

const NETCAT_MODULE_LOGGING_ALL_USERS = "All Users";
const NETCAT_MODULE_LOGGING_SHOW_USER = "user which performed the action";
const NETCAT_MODULE_LOGGING_OVER_PERIOD = "over period";
