<?php

const NETCAT_MODULE_LOGGING_DESCRIPTION = "Логирование системных событий";

const NETCAT_MODULE_LOGGING_DATA_ID = "#";
const NETCAT_MODULE_LOGGING_DATA_EVENT = "Событие";
const NETCAT_MODULE_LOGGING_DATA_INFO = "Информация";
const NETCAT_MODULE_LOGGING_DATA_DATE = "Дата события";
const NETCAT_MODULE_LOGGING_DATA_USER = "Пользователь";
const NETCAT_MODULE_LOGGING_DATA_SYSTEM = "система";
const NETCAT_MODULE_LOGGING_DATA_IP = "IP-адрес";

const NETCAT_MODULE_LOGGING_BUTTON_CLEAR = "Очистить";
const NETCAT_MODULE_LOGGING_BUTTON_CANCEL = "Отменить";
const NETCAT_MODULE_LOGGING_BUTTON_SORT = "Отобразить";

const NETCAT_MODULE_LOGGING_NOTICE_CLEAR = "Очистить все данные логирования?";

const NETCAT_MODULE_LOGGING_SHOW_PARAMETERS = "Параметры отображения";
const NETCAT_MODULE_LOGGING_SHOW_SORT_BY = "сортировать по";
const NETCAT_MODULE_LOGGING_SHOW_SORT_BY_DATE = "дате события";
const NETCAT_MODULE_LOGGING_SHOW_SORT_BY_EVENT = "названию события";
const NETCAT_MODULE_LOGGING_SHOW_SORT_BY_USER = "пользователю";
const NETCAT_MODULE_LOGGING_SHOW_SORT_DIR = "порядок сортировки";
const NETCAT_MODULE_LOGGING_SHOW_SORT_DIR_ASC = "по возрастанию";
const NETCAT_MODULE_LOGGING_SHOW_SORT_DIR_DESC = "по убыванию";
const NETCAT_MODULE_LOGGING_SHOW_ONLY_ACTION = "отобразить действие";
const NETCAT_MODULE_LOGGING_SHOW_ONLY_ACTION_NONE = "-- действие не задано --";
const NETCAT_MODULE_LOGGING_SHOW_ONLY_ESSENCE = "отобразить сущность";
const NETCAT_MODULE_LOGGING_SHOW_ONLY_ESSENCE_NONE = "-- сущность не задана --";

const NETCAT_MODULE_LOGGING_EVENT_TYPE_ADD = "добавление";
const NETCAT_MODULE_LOGGING_EVENT_TYPE_UPDATE = "изменение";
const NETCAT_MODULE_LOGGING_EVENT_TYPE_DROP = "удаление";
const NETCAT_MODULE_LOGGING_EVENT_TYPE_CHECK = "включение";
const NETCAT_MODULE_LOGGING_EVENT_TYPE_UNCHECK = "выключение";
const NETCAT_MODULE_LOGGING_EVENT_TYPE_AUTHORIZE = "авторизация";
const NETCAT_MODULE_LOGGING_EVENT_TYPE_BLOCK = "блокирование";
const NETCAT_MODULE_LOGGING_EVENT_TYPE_UNBLOCK = "разблокирование";

const NETCAT_MODULE_LOGGING_EVENT_ESSENCE_CATALOGUE = "сайт";
const NETCAT_MODULE_LOGGING_EVENT_ESSENCE_SUBDIVISION = "раздел";
const NETCAT_MODULE_LOGGING_EVENT_ESSENCE_SUBCLASS = "инфоблок";
const NETCAT_MODULE_LOGGING_EVENT_ESSENCE_CLASS = "компонент";
const NETCAT_MODULE_LOGGING_EVENT_ESSENCE_CLASSTEMPLATE = "шаблон компонента";
const NETCAT_MODULE_LOGGING_EVENT_ESSENCE_MESSAGE = "объект";
const NETCAT_MODULE_LOGGING_EVENT_ESSENCE_SYSTEMTABLE = "системная таблица";
const NETCAT_MODULE_LOGGING_EVENT_ESSENCE_TEMPLATE = "макет";
const NETCAT_MODULE_LOGGING_EVENT_ESSENCE_USER = "пользователь";
const NETCAT_MODULE_LOGGING_EVENT_ESSENCE_MODULE = "модуль";
const NETCAT_MODULE_LOGGING_EVENT_ESSENCE_COMMENT = "комментарий";
const NETCAT_MODULE_LOGGING_EVENT_ESSENCE_WIDGETCLASS = "виджет";
const NETCAT_MODULE_LOGGING_EVENT_ESSENCE_FIELD = "поле";
const NETCAT_MODULE_LOGGING_EVENT_ESSENCE_CLASSIFICATOR = "список";
const NETCAT_MODULE_LOGGING_EVENT_ESSENCE_CLASSIFICATORITEM = "элемент списка";
const NETCAT_MODULE_LOGGING_EVENT_ESSENCE_TEMPLATEPARTIAL = "врезка";

const NETCAT_MODULE_LOGGING_QUOTE1 = "«";
const NETCAT_MODULE_LOGGING_QUOTE2 = "»";

const NETCAT_MODULE_LOGGING_ALL_USERS = "все пользователи";
const NETCAT_MODULE_LOGGING_SHOW_USER = "совершивший действие пользователь";
const NETCAT_MODULE_LOGGING_OVER_PERIOD = "за период";
